openapi: 3.0.3
info:
  title: Sociogrammers Student Query Management System - OpenAPI 3.0
  description: This API describes the endpoints that have been created to integrate discourse & Gchat and for enhancement of existing Online Ticketing app for IITM BS programme.
  version: "0.0.1"

servers:
  - url: http://127.0.0.1:5000


paths:
  /posts.json:
    description: "API endpoints to performa various tasks on discourse."
    post:
      description: 'Api for creating a query or replying on a query on discourse'
      tags:
        - Discourse API Endpoints
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - raw
              properties:
                title:
                  type: string
                raw:
                  type: string
                topic_id:
                  type: integer
                category:
                  type: integer
                created_at:
                  type: string
                reply_to_post_number:
                  type: integer
      responses:
        '200':
          description: post created
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  username:
                    type: string
                  avatar_template:
                    type: string
                  created_at:
                    type: string
                  raw:
                    type: string
                  cooked:
                    type: string
                  post_number:
                    type: integer
                  post_type:
                    type: integer
                  updated_at:
                    type: string
                  reply_count:
                    type: integer
                  reply_to_post_number:
                    type: string
                  quote_count:
                    type: integer
                  incoming_link_count:
                    type: integer
                  reads:
                    type: integer
                  readers_count:
                    type: integer
                  score:
                    type: number
                  yours:
                    type: boolean
                  topic_id:
                    type: integer
                  topic_slug:
                    type: string
                  display_username:
                    type: string
                  primary_group_name:
                    type:
                    - string
                    - 'null'
                  flair_name:
                    type: string
                  flair_url:
                    type: string
                  flair_bg_color:
                    type: string
                  flair_color:
                    type: string
                  flair_group_id:
                    type: string
                  version:
                    type: integer
                  can_edit:
                    type: boolean
                  can_delete:
                    type: boolean
                  can_recover:
                    type: boolean
                  can_see_hidden_post:
                    type: boolean
                  can_wiki:
                    type: boolean
                  user_title:
                    type: string
                  bookmarked:
                    type: boolean
                  actions_summary:
                    type: array
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        id:
                          type: integer
                        can_act:
                          type: boolean
                      required:
                      - id
                      - can_act
                  moderator:
                    type: boolean
                  admin:
                    type: boolean
                  staff:
                    type: boolean
                  user_id:
                    type: integer
                  draft_sequence:
                    type: integer
                  hidden:
                    type: boolean
                  trust_level:
                    type: integer
                  deleted_at:
                    type: string
                  user_deleted:
                    type: boolean
                  edit_reason:
                    type: string
                  can_view_edit_history:
                    type: boolean
                  wiki:
                    type: boolean
                  reviewable_id:
                    type: string
                  reviewable_score_count:
                    type: integer
                  reviewable_score_pending_count:
                    type: integer
                  mentioned_users:
                    type: array
                    items: {}
                required:
                - id
                - name
                - username
                - avatar_template
                - created_at
                - cooked
                - post_number
                - post_type
                - updated_at
                - reply_count
                - reply_to_post_number
                - quote_count
                - incoming_link_count
                - reads
                - readers_count
                - score
                - yours
                - topic_id
                - topic_slug
                - display_username
                - primary_group_name
                - flair_name
                - flair_url
                - flair_bg_color
                - flair_color
                - version
                - can_edit
                - can_delete
                - can_recover
                - can_wiki
                - user_title
                - bookmarked
                - actions_summary
                - moderator
                - admin
                - staff
                - user_id
                - draft_sequence
                - hidden
                - trust_level
                - deleted_at
                - user_deleted
                - edit_reason
                - can_view_edit_history
                - wiki
                - reviewable_id
                - reviewable_score_count
                - reviewable_score_pending_count

  /posts/{id}/locked.json:
    put:
      description: Lock a post from being edited
      tags:
      - Discourse API Endpoints
      operationId: lockPost
      parameters:
      - name: Api-Key
        in: header
        required: true
        schema:
          type: string
      - name: Api-Username
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                locked:
                  type: string
              required:
              - locked
      responses:
        '200':
          description: post updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  locked:
                    type: boolean
  
  /posts:
    post:
      summary: Create a new post with tags.
      tags:
        - API endpoints within Online Ticketing App.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Post created successfully.
        '400':
          description: Invalid input.
  
  /search_users:
    get:
      summary: Search for users to tag.
      parameters:
        - in: query
          name: search_term
          schema:
            type: string
          required: true
          description: The search term for the user.
      responses:
        '200':
          description: Search results returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                    id:
                      type: string
        '404':
          description: No users found.

  /messages:
    post:
      summary: Send a Google Chat message.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessage'
      responses:
        '201':
          description: Message sent successfully.
        '400':
          description: Invalid input.

  /messages/{messageId}:
    get:
      summary: Retrieve a specific message by ID.
      parameters:
        - in: path
          name: messageId
          required: true
          schema:
            type: string
          description: Unique ID of the message.
      responses:
        '200':
          description: Message retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessage'
        '404':
          description: Message not found.

  /support_staff/activity_status:
    get:
      summary: Get the activity status of all support staff members.
      description: Retrieve a list of support staff members along with their current activity status.
      responses:
        '200':
          description: An array of support staff and their activity statuses.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StaffActivityStatus'
