openapi: 3.0.3
info:
  title: Sociogrammers Student Query Management System - OpenAPI 3.0
  description: This API describes the endpoints available for the software created by Team Sociogrammers for the Software Engineering Project.
  version: "0.0.1"

servers:
  - url: http://127.0.0.1:5000


paths:
  /send_gchat_msg:
      post:
        tags:
          - Support Staff
        summary: Send message to Gchat if priority is beyond 5.
        operationId: postAndCheckPriorityMeasure
        requestBody:
          content:
            application/json:
              schema:
                type: object
                required:
                  - ticket_id
                  - priority_measure
                properties:
                  ticket_id:
                    type: integer
                    example: 3
                  priority_measure:
                    type: integer
                    example: 6
                  message:
                    type: string
                    example: "Priority measure exceeded 5. Immediate action required!"
                  webhook_url:
                    type: string
                    format: uri
                    example: "https://example.com/gchat/webhook"
        responses:
          '200':
            description: Successfully posted ticket and checked priority measure.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Message posted successfully."
          '400':
            description: Invalid request body.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Invalid request body. Please provide valid ticket ID and priority measure."
          '500':
            description: Internal server error.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Internal server error. Please try again later."

  /submit_previous_discussion_links:
    post:
      tags:
        - Support Staff
      summary: Submit clickable links for a previous discussion.
      operationId: postSubmitPreviousDiscussionLinks
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - post_id
              properties:
                post_id:
                  type: integer
                  example: 123
                discussion_links:
                  type: array
                  items:
                    type: string
                    format: uri
                    example: "https://example.com/previous_discussion1"
      responses:
        '200':
          description: Successfully submitted previous discussion links.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Previous discussion links submitted successfully."
        '400':
          description: Invalid request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid request body. Please provide a valid post ID."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error. Please try again later."

  /check_flagged_posts:
      post:
        tags:
          - Support Manager
        summary: Check for flagged posts and send message to Support Manager.
        operationId: postCheckFlaggedPosts
        requestBody:
          content:
            application/json:
              schema:
                type: object
                required:
                  - post_id
                  - flag_message
                  - user_id
                properties:
                  post_id:
                    type: integer
                    example: 123
                  flag_message:
                    type: string
                    example: "This post contains inappropriate content."
                  user_id:
                    type: integer
                    example: 456
                  message:
                    type: string
                    example: "A post has been flagged. Please check immediately."
                  webhook_url:
                    type: string
                    format: uri
                    example: "https://example.com/support_manager/webhook"
        responses:
          '200':
            description: Successfully sent message to Support Manager.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Message sent to Support Manager about the flagged post."
          '400':
            description: Invalid request body.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Invalid request body. Please provide valid post ID, flag message, and user ID."
          '500':
            description: Internal server error.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Internal server error. Please try again later."
